#!/usr/bin/env python3
"""Build the crawlable parts of the public site from the published data.

The dashboard renders its cards in the browser from JSON, so a crawler that
does not run JavaScript sees an empty page. This stage writes:

* a static list of the latest updates into ``docs/index.html`` between the
  ``STATIC-LATEST`` markers, inside the cards container -- ``app.js`` replaces
  it with the interactive cards as soon as the data loads, so visitors and
  crawlers are shown the same records;
* ``docs/sitemap.xml`` listing the indexable pages.

It reads only ``docs/data/legal_updates.json`` and changes nothing in it.
Output is deterministic for a given input (no wall-clock timestamps), so an
unchanged corpus produces no diff. Every record field is untrusted: text is
HTML/XML-escaped and only http(s) source URLs are emitted as links.
"""

from __future__ import annotations

import argparse
import json
import sys
from datetime import date, datetime
from html import escape
from pathlib import Path
from typing import Any, Mapping, Sequence
from xml.sax.saxutils import escape as xml_escape

SCRIPTS_DIR = Path(__file__).resolve().parent
if str(SCRIPTS_DIR) not in sys.path:
    sys.path.insert(0, str(SCRIPTS_DIR))

from alert_common import (  # noqa: E402
    JST,
    SITE_URL,
    clean_text,
    safe_http_url,
    source_display_name,
    strict_iso_date,
    summary_is_ai,
    write_text_atomic,
)

REPO_ROOT = SCRIPTS_DIR.parent
DOCS_DIR = REPO_ROOT / "docs"
DATA_PATH = DOCS_DIR / "data" / "legal_updates.json"
INDEX_PATH = DOCS_DIR / "index.html"
SITEMAP_PATH = DOCS_DIR / "sitemap.xml"

STATIC_START = "<!-- STATIC-LATEST:START (generated by scripts/build_public_pages.py; do not edit) -->"
STATIC_END = "<!-- STATIC-LATEST:END -->"
STATIC_LATEST_COUNT = 20
SUMMARY_MAX_CHARS = 320

# Pages a search engine should index, relative to SITE_URL. The thank-you
# page is noindex and the feeds are not pages, so neither is listed.
STATIC_SITEMAP_PATHS = ("legal/disclaimer_en.html", "legal/disclaimer_ja.html")


def load_items(path: Path) -> list[dict[str, Any]]:
    data = json.loads(path.read_text(encoding="utf-8"))
    if not isinstance(data, list):
        raise ValueError(f"{path} must contain a JSON list")
    return [item for item in data if isinstance(item, dict)]


def latest_checked(items: Sequence[Mapping[str, Any]]) -> date | None:
    dates = [d for d in (strict_iso_date(item.get("last_checked")) for item in items) if d]
    return max(dates) if dates else None


def latest_items(items: Sequence[Mapping[str, Any]], today: date, count: int) -> list[Mapping[str, Any]]:
    """Newest official publications first; undated and future-dated items are skipped."""
    dated = []
    for index, item in enumerate(items):
        published = strict_iso_date(item.get("published_at"))
        if published and published <= today and clean_text(item.get("title_en")):
            dated.append((published, index, item))
    # Ties keep the published file's relevance order.
    dated.sort(key=lambda row: (-row[0].toordinal(), row[1]))
    return [item for _, _, item in dated[:count]]


def shorten(text: str, limit: int) -> str:
    if len(text) <= limit:
        return text
    cut = text[: limit - 1].rsplit(" ", 1)[0].rstrip(" ,;:")
    return cut + "…"


def render_static_item(item: Mapping[str, Any]) -> str:
    title = escape(clean_text(item.get("title_en")))
    meta = [
        clean_text(item.get("published_at")),
        source_display_name(item.get("source_name")),
        clean_text(item.get("area")),
        clean_text(item.get("stage")),
    ]
    meta_html = " · ".join(escape(part) for part in meta if part)
    lines = ['        <li class="static-latest-item">']
    url = safe_http_url(item.get("source_url"))
    if url:
        lines.append(
            f'          <a class="static-latest-title" href="{escape(url)}" '
            f'target="_blank" rel="noopener noreferrer">{title}</a>'
        )
    else:
        lines.append(f'          <span class="static-latest-title">{title}</span>')
    if meta_html:
        lines.append(f'          <span class="static-latest-meta">{meta_html}</span>')
    # Rule-based previews are the same template sentence on every item, so
    # only an AI summary adds anything worth showing here.
    if summary_is_ai(item):
        summary = escape(shorten(clean_text(item.get("summary_en")), SUMMARY_MAX_CHARS))
        lines.append(f'          <p class="static-latest-summary">{summary} <em>(AI summary)</em></p>')
    lines.append("        </li>")
    return "\n".join(lines)


def render_static_latest(items: Sequence[Mapping[str, Any]], updated: date | None) -> str:
    heading_note = f" — checked {updated.isoformat()}" if updated else ""
    body = "\n".join(render_static_item(item) for item in items)
    return (
        f"{STATIC_START}\n"
        '      <section class="static-latest" aria-labelledby="static-latest-title">\n'
        f'        <h2 id="static-latest-title">Latest Japan legal &amp; regulatory updates{heading_note}</h2>\n'
        '        <p class="static-latest-note">Newest official publications from the Japanese sources this '
        "dashboard monitors. Titles and AI summaries are unofficial English monitoring aids, not legal "
        "advice; each link opens the original Japanese official source, which remains authoritative.</p>\n"
        '        <ol class="static-latest-list">\n'
        f"{body}\n"
        "        </ol>\n"
        "      </section>\n"
        f"      {STATIC_END}"
    )


def replace_static_block(html: str, block: str) -> str:
    start = html.find(STATIC_START)
    end = html.find(STATIC_END)
    if start < 0 or end < 0 or end < start or html.count(STATIC_START) != 1 or html.count(STATIC_END) != 1:
        raise ValueError("index.html must contain exactly one STATIC-LATEST start/end marker pair")
    return html[:start] + block + html[end + len(STATIC_END):]


def render_sitemap(updated: date | None) -> str:
    entries = [(SITE_URL, updated)] + [(SITE_URL + path, None) for path in STATIC_SITEMAP_PATHS]
    lines = ['<?xml version="1.0" encoding="UTF-8"?>', '<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">']
    for loc, lastmod in entries:
        lines.append("  <url>")
        lines.append(f"    <loc>{xml_escape(loc)}</loc>")
        if lastmod:
            lines.append(f"    <lastmod>{lastmod.isoformat()}</lastmod>")
        lines.append("  </url>")
    lines.append("</urlset>")
    return "\n".join(lines) + "\n"


def write_if_changed(path: Path, text: str) -> bool:
    if path.exists() and path.read_text(encoding="utf-8") == text:
        return False
    write_text_atomic(path, text)
    return True


def build(data_path: Path, index_path: Path, sitemap_path: Path, today: date) -> dict[str, Any]:
    items = load_items(data_path)
    updated = latest_checked(items)
    latest = latest_items(items, today, STATIC_LATEST_COUNT)
    html = index_path.read_text(encoding="utf-8")
    new_html = replace_static_block(html, render_static_latest(latest, updated))
    return {
        "static_latest_items": len(latest),
        "index_changed": write_if_changed(index_path, new_html),
        "sitemap_changed": write_if_changed(sitemap_path, render_sitemap(updated)),
    }


def main(argv: Sequence[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--data", type=Path, default=DATA_PATH)
    parser.add_argument("--index", type=Path, default=INDEX_PATH)
    parser.add_argument("--sitemap", type=Path, default=SITEMAP_PATH)
    parser.add_argument("--today", type=date.fromisoformat, default=None, help="JST date (YYYY-MM-DD)")
    args = parser.parse_args(argv)
    today = args.today or datetime.now(JST).date()
    result = build(args.data, args.index, args.sitemap, today)
    print(json.dumps(result, sort_keys=True))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
