#!/usr/bin/env python3
"""Build the crawlable parts of the public site from the published data.

The dashboard renders its cards in the browser from JSON, so a crawler that
does not run JavaScript sees an empty page. This stage writes:

* a static list of the latest updates into ``docs/index.html`` between the
  ``STATIC-LATEST`` markers, inside the cards container -- ``app.js`` replaces
  it with the interactive cards as soon as the data loads, so visitors and
  crawlers are shown the same records;
* a "Browse by area" navigation into ``docs/index.html`` between the
  ``AREA-NAV`` markers;
* one static landing page per monitoring area under ``docs/areas/<slug>/``
  and a cross-area page of open public comments under
  ``docs/public-comments/``;
* ``docs/sitemap.xml`` listing the indexable pages.

It reads only ``docs/data/legal_updates.json`` and changes nothing in it.
Output is deterministic for a given input and JST date (no wall-clock
timestamps), so an unchanged corpus produces no diff. Every record field is
untrusted: text is HTML/XML-escaped and only http(s) source URLs are emitted
as links.
"""

from __future__ import annotations

import argparse
import json
import sys
from collections import Counter
from dataclasses import dataclass
from datetime import date, datetime
from html import escape
from pathlib import Path
from typing import Any, Mapping, Sequence
from urllib.parse import urlencode
from xml.sax.saxutils import escape as xml_escape

SCRIPTS_DIR = Path(__file__).resolve().parent
if str(SCRIPTS_DIR) not in sys.path:
    sys.path.insert(0, str(SCRIPTS_DIR))

from alert_common import (  # noqa: E402
    CHANNELS,
    JST,
    SITE_URL,
    Channel,
    clean_text,
    comment_deadline_display,
    item_in_channel,
    open_comment_deadline,
    safe_http_url,
    source_display_name,
    strict_iso_date,
    summary_is_ai,
    write_text_atomic,
)

REPO_ROOT = SCRIPTS_DIR.parent
DOCS_DIR = REPO_ROOT / "docs"
DATA_PATH = DOCS_DIR / "data" / "legal_updates.json"
INDEX_PATH = DOCS_DIR / "index.html"
SITEMAP_PATH = DOCS_DIR / "sitemap.xml"

STATIC_START = "<!-- STATIC-LATEST:START (generated by scripts/build_public_pages.py; do not edit) -->"
STATIC_END = "<!-- STATIC-LATEST:END -->"
AREA_NAV_START = "<!-- AREA-NAV:START (generated by scripts/build_public_pages.py; do not edit) -->"
AREA_NAV_END = "<!-- AREA-NAV:END -->"
STATIC_LATEST_COUNT = 20
AREA_LATEST_COUNT = 30
AREA_OPEN_COMMENTS_COUNT = 20
AREA_TOP_SOURCES = 6
SUMMARY_MAX_CHARS = 320

# Shared with docs/index.html; bump both together when style.css changes.
STYLE_CACHE_BUSTER = "lang-switch-20261008"
ANALYTICS_CACHE_BUSTER = "analytics-20261006"

AREAS_DIR_NAME = "areas"
PUBLIC_COMMENTS_DIR_NAME = "public-comments"

# Pages a search engine should index, relative to SITE_URL. The thank-you
# page is noindex and the feeds are not pages, so neither is listed.
STATIC_SITEMAP_PATHS = ("legal/disclaimer_en.html", "legal/disclaimer_ja.html")


@dataclass(frozen=True)
class AreaPage:
    """A landing page for one monitoring channel.

    ``slug`` becomes a public URL: never rename one that has been published.
    The heading uses the words people search with; the intro describes only
    what the area covers, never what any development means for a reader.
    """

    channel: str
    slug: str
    heading: str
    topics: str


AREA_PAGES: tuple[AreaPage, ...] = (
    AreaPage(
        "dataprivacyai", "data-privacy-ai", "Japan Data Privacy & AI Regulation Updates",
        "personal information protection, AI governance, cybersecurity, telecommunications, "
        "broadcasting, and digital administration",
    ),
    AreaPage(
        "financeaml", "finance-aml", "Japan Financial Regulation & AML Updates",
        "banking, securities markets, insurance, payments, anti-money laundering, foreign exchange, "
        "and related tax administration",
    ),
    AreaPage(
        "antitrustfairtrade", "antitrust-fair-trade", "Japan Antitrust & Competition Law Updates",
        "competition law enforcement, merger review, fair-trade guidelines, and subcontracting rules",
    ),
    AreaPage(
        "consumeradvertising", "consumer-advertising", "Japan Consumer Protection & Advertising Regulation Updates",
        "consumer contracts, labelling and advertising rules, product safety, and consumer administration",
    ),
    AreaPage(
        "laboremployment", "labor-employment", "Japan Employment & Labor Law Updates",
        "working conditions, wages, social insurance, occupational safety, and employment of foreign workers",
    ),
    AreaPage(
        "corporategovernance", "corporate-governance", "Japan Corporate Law & Governance Updates",
        "company law, commercial registration, corporate disclosure, and corporate governance",
    ),
    AreaPage(
        "economicsecurityfdi", "economic-security-fdi", "Japan Economic Security & FDI Regulation Updates",
        "foreign direct investment screening, foreign exchange controls, export controls, and economic security",
    ),
    AreaPage(
        "taxstampduty", "tax-stamp-duty", "Japan Tax Law Updates",
        "national tax statutes, cabinet and ministerial orders on tax, stamp duty, and tax administration",
    ),
    AreaPage(
        "healthcarepharma", "healthcare-pharmaceuticals", "Japan Healthcare & Pharmaceutical Regulation Updates",
        "pharmaceuticals, medical devices, drug safety information, and healthcare administration",
    ),
    AreaPage(
        "energyenvironment", "energy-environment", "Japan Energy & Environmental Regulation Updates",
        "electricity and gas, renewable energy, decarbonisation, waste, chemicals, and environmental protection",
    ),
    AreaPage(
        "foodagriculture", "food-agriculture", "Japan Food & Agriculture Regulation Updates",
        "food safety and standards, agriculture, forestry, fisheries, quarantine, and agricultural trade",
    ),
    AreaPage(
        "transportinfrastructure", "transport-infrastructure", "Japan Transport & Infrastructure Regulation Updates",
        "road, rail, aviation, maritime transport, logistics, and construction",
    ),
    AreaPage(
        "realestatelanduse", "real-estate-land-use", "Japan Real Estate & Land Use Regulation Updates",
        "real estate transactions, land use, urban planning, and building standards",
    ),
    AreaPage(
        "publicsafetydisaster", "public-safety-disaster", "Japan Public Safety & Disaster Management Updates",
        "disaster prevention and response, fire safety, and public safety",
    ),
)

CHANNEL_BY_VALUE: dict[str, Channel] = {channel.value: channel for channel in CHANNELS}

PUBLIC_COMMENTS_HEADING = "Open Japanese Public Comments (Consultations) and Deadlines"

MONITORING_NOTICE = (
    "Titles and AI summaries are unofficial English monitoring aids, not legal advice or official "
    "translations. Each link opens the original Japanese official source, which remains authoritative."
)
AREA_LABEL_NOTICE = (
    "Area labels are assigned by keyword rules for triage, so this page may miss relevant items "
    "or include marginal ones."
)


# ---------------------------------------------------------------- data helpers


def load_items(path: Path) -> list[dict[str, Any]]:
    data = json.loads(path.read_text(encoding="utf-8"))
    if not isinstance(data, list):
        raise ValueError(f"{path} must contain a JSON list")
    return [item for item in data if isinstance(item, dict)]


def latest_checked(items: Sequence[Mapping[str, Any]]) -> date | None:
    dates = [d for d in (strict_iso_date(item.get("last_checked")) for item in items) if d]
    return max(dates) if dates else None


def latest_items(items: Sequence[Mapping[str, Any]], today: date, count: int) -> list[Mapping[str, Any]]:
    """Newest official publications first; undated and future-dated items are skipped."""
    dated = []
    for index, item in enumerate(items):
        published = strict_iso_date(item.get("published_at"))
        if published and published <= today and clean_text(item.get("title_en")):
            dated.append((published, index, item))
    # Ties keep the published file's relevance order.
    dated.sort(key=lambda row: (-row[0].toordinal(), row[1]))
    return [item for _, _, item in dated[:count]]


def open_comments(items: Sequence[Mapping[str, Any]], today: date) -> list[Mapping[str, Any]]:
    """Open consultations with a trusted deadline, soonest deadline first."""
    rows = []
    for index, item in enumerate(items):
        deadline = open_comment_deadline(item, today)
        if deadline and clean_text(item.get("title_en")):
            rows.append((deadline[0], index, item))
    rows.sort(key=lambda row: (row[0].toordinal(), row[1]))
    return [item for _, _, item in rows]


def top_sources(items: Sequence[Mapping[str, Any]], count: int) -> list[tuple[str, int]]:
    counter = Counter(source_display_name(item.get("source_name")) for item in items)
    counter.pop("", None)
    # Most items first; ties alphabetical so the order is stable.
    return sorted(counter.items(), key=lambda row: (-row[1], row[0]))[:count]


def area_items(items: Sequence[Mapping[str, Any]], page: AreaPage) -> list[Mapping[str, Any]]:
    channel = CHANNEL_BY_VALUE[page.channel]
    return [item for item in items if item_in_channel(item, channel)]


def area_page_path(page: AreaPage) -> str:
    return f"{AREAS_DIR_NAME}/{page.slug}/"


def dashboard_area_url(page: AreaPage) -> str:
    return SITE_URL + "?" + urlencode({"area": CHANNEL_BY_VALUE[page.channel].area})


# ------------------------------------------------------------------ rendering


def shorten(text: str, limit: int) -> str:
    if len(text) <= limit:
        return text
    cut = text[: limit - 1].rsplit(" ", 1)[0].rstrip(" ,;:")
    return cut + "…"


def render_static_item(item: Mapping[str, Any], *, show_area: bool = True, show_deadline: bool = False) -> str:
    title = escape(clean_text(item.get("title_en")))
    meta = [
        clean_text(item.get("published_at")),
        source_display_name(item.get("source_name")),
        clean_text(item.get("area")) if show_area else "",
        clean_text(item.get("stage")),
    ]
    meta_html = " · ".join(escape(part) for part in meta if part)
    lines = ['        <li class="static-latest-item">']
    url = safe_http_url(item.get("source_url"))
    if url:
        lines.append(
            f'          <a class="static-latest-title" href="{escape(url)}" '
            f'target="_blank" rel="noopener noreferrer">{title}</a>'
        )
    else:
        lines.append(f'          <span class="static-latest-title">{title}</span>')
    if meta_html:
        lines.append(f'          <span class="static-latest-meta">{meta_html}</span>')
    if show_deadline:
        deadline = comment_deadline_display(item.get("comment_deadline"))
        if deadline:
            lines.append(f'          <span class="static-latest-deadline">Comments due: {escape(deadline)}</span>')
    # Rule-based previews are the same template sentence on every item, so
    # only an AI summary adds anything worth showing here.
    if summary_is_ai(item):
        summary = escape(shorten(clean_text(item.get("summary_en")), SUMMARY_MAX_CHARS))
        lines.append(f'          <p class="static-latest-summary">{summary} <em>(AI summary)</em></p>')
    lines.append("        </li>")
    return "\n".join(lines)


def render_item_list(items: Sequence[Mapping[str, Any]], **options: bool) -> str:
    body = "\n".join(render_static_item(item, **options) for item in items)
    return f'        <ol class="static-latest-list">\n{body}\n        </ol>'


def render_static_latest(items: Sequence[Mapping[str, Any]], updated: date | None) -> str:
    heading_note = f" — checked {updated.isoformat()}" if updated else ""
    return (
        f"{STATIC_START}\n"
        '      <section class="static-latest" aria-labelledby="static-latest-title">\n'
        f'        <h2 id="static-latest-title">Latest Japan legal &amp; regulatory updates{heading_note}</h2>\n'
        '        <p class="static-latest-note">Newest official publications from the Japanese sources this '
        "dashboard monitors. Titles and AI summaries are unofficial English monitoring aids, not legal "
        "advice; each link opens the original Japanese official source, which remains authoritative.</p>\n"
        f"{render_item_list(items)}\n"
        "      </section>\n"
        f"      {STATIC_END}"
    )


def render_area_links(prefix: str, current: str = "") -> str:
    """Links to every area page plus the public-comments page.

    ``prefix`` is the relative path from the page being written to the site
    root, so the links work on the live site and in a local preview alike.
    """
    links = []
    for page in AREA_PAGES:
        label = escape(CHANNEL_BY_VALUE[page.channel].label)
        if page.slug == current:
            links.append(f'<li><span aria-current="page">{label}</span></li>')
        else:
            links.append(f'<li><a href="{prefix}{area_page_path(page)}">{label}</a></li>')
    if current == PUBLIC_COMMENTS_DIR_NAME:
        links.append('<li><span aria-current="page">Open public comments</span></li>')
    else:
        links.append(f'<li><a href="{prefix}{PUBLIC_COMMENTS_DIR_NAME}/">Open public comments</a></li>')
    return "\n".join("          " + link for link in links)


def render_area_nav() -> str:
    return (
        f"{AREA_NAV_START}\n"
        '    <nav class="area-nav" aria-labelledby="area-nav-title">\n'
        '      <h2 id="area-nav-title" class="area-nav-title">Browse Japan legal updates by area</h2>\n'
        '        <ul class="area-nav-list">\n'
        f"{render_area_links('./')}\n"
        "        </ul>\n"
        "    </nav>\n"
        f"    {AREA_NAV_END}"
    )


def replace_block(html: str, start_marker: str, end_marker: str, block: str) -> str:
    start = html.find(start_marker)
    end = html.find(end_marker)
    if start < 0 or end < start or html.count(start_marker) != 1 or html.count(end_marker) != 1:
        raise ValueError(f"index.html must contain exactly one {start_marker[:20]}... marker pair")
    return html[:start] + block + html[end + len(end_marker):]


def replace_static_block(html: str, block: str) -> str:
    return replace_block(html, STATIC_START, STATIC_END, block)


def json_ld(data: Mapping[str, Any]) -> str:
    # "</" cannot close the script element when escaped as "<\/".
    return json.dumps(data, ensure_ascii=False, indent=2).replace("</", "<\\/")


def render_page(
    *,
    path: str,
    title: str,
    description: str,
    heading: str,
    breadcrumb: str,
    body: str,
    current: str,
) -> str:
    """A complete static page at ``SITE_URL + path`` (two directories deep)."""
    prefix = "../../" if path.count("/") == 2 else "../"
    url = SITE_URL + path
    structured = json_ld(
        {
            "@context": "https://schema.org",
            "@type": "CollectionPage",
            "name": heading,
            "description": description,
            "url": url,
            "inLanguage": "en",
            "isPartOf": {"@type": "WebSite", "name": "Japan Legal Reform Watch by LegalOS", "url": SITE_URL},
            "breadcrumb": {
                "@type": "BreadcrumbList",
                "itemListElement": [
                    {"@type": "ListItem", "position": 1, "name": "Japan Legal Reform Watch", "item": SITE_URL},
                    {"@type": "ListItem", "position": 2, "name": breadcrumb, "item": url},
                ],
            },
        }
    )
    return f"""<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <title>{escape(title)}</title>
  <meta name="description" content="{escape(description)}" />
  <link rel="canonical" href="{escape(url)}" />
  <meta property="og:type" content="website" />
  <meta property="og:site_name" content="Japan Legal Reform Watch by LegalOS" />
  <meta property="og:title" content="{escape(heading)}" />
  <meta property="og:description" content="{escape(description)}" />
  <meta property="og:url" content="{escape(url)}" />
  <meta name="twitter:card" content="summary" />
  <script type="application/ld+json">
{structured}
  </script>
  <link rel="stylesheet" href="{prefix}style.css?v={STYLE_CACHE_BUSTER}" />
</head>
<body class="area-page">
  <header class="site-header">
    <div class="container header-inner">
      <div class="brand">
        <p class="area-page-brand"><a href="{prefix}">Japan Legal Reform Watch <span class="brand-by">by LegalOS</span></a></p>
        <p class="tagline">Free Japan Legal &amp; Regulatory Update Monitor</p>
      </div>
      <div class="header-actions">
        <a class="header-link" href="{prefix}">Open the dashboard</a>
      </div>
    </div>
  </header>

  <section class="trust-section" aria-label="Reliability notice">
    <div class="container">
      <div class="trust-notice" role="note">
        <strong>Reliability note</strong>
        <p>{escape(MONITORING_NOTICE)}</p>
      </div>
    </div>
  </section>

  <main class="container area-page-main">
    <nav class="area-breadcrumb" aria-label="Breadcrumb">
      <a href="{prefix}">Japan Legal Reform Watch</a> &rsaquo; <span aria-current="page">{escape(breadcrumb)}</span>
    </nav>
    <h1 class="area-page-title">{escape(heading)}</h1>
{body}
    <nav class="area-nav" aria-labelledby="area-nav-title">
      <h2 id="area-nav-title" class="area-nav-title">Other areas</h2>
        <ul class="area-nav-list">
{render_area_links(prefix, current)}
        </ul>
    </nav>
  </main>

  <footer class="site-footer">
    <div class="container footer-inner">
      <div class="footer-brand">
        <strong>Japan Legal Reform Watch by LegalOS</strong>
        <p>Created by Legal GPT. Explore more Japan legal updates and legal-tech tools.</p>
      </div>
      <div class="footer-navs">
        <nav class="footer-links footer-product-links" aria-label="Legal GPT links">
          <a href="https://legal-gpt.com/" target="_blank" rel="noopener noreferrer">Legal GPT</a>
          <a href="https://legal-gpt.com/japan-legal-update-monitor/" target="_blank" rel="noopener noreferrer">Learn more about Japan Legal Reform Watch</a>
        </nav>
        <nav class="footer-links footer-legal-links" aria-label="Legal">
          <a href="{prefix}legal/disclaimer_en.html">Legal Notice / Disclaimer (EN)</a>
          <a href="{prefix}legal/disclaimer_ja.html">免責事項 (JA)</a>
        </nav>
      </div>
    </div>
    <div class="container footer-bottom">
      <small>This site provides English summaries for informational purposes only. It is not an official
        translation and not legal advice. See the full Legal Notice for details.</small>
    </div>
  </footer>

  <script src="{prefix}analytics.js?v={ANALYTICS_CACHE_BUSTER}"></script>
</body>
</html>
"""


def render_area_page(page: AreaPage, items: Sequence[Mapping[str, Any]], today: date) -> str:
    channel = CHANNEL_BY_VALUE[page.channel]
    in_area = area_items(items, page)
    updated = latest_checked(in_area)
    open_items = open_comments(in_area, today)
    latest = latest_items(in_area, today, AREA_LATEST_COUNT)
    ai_count = sum(1 for item in in_area if summary_is_ai(item))
    description = (
        f"English monitoring of Japanese {page.topics}: the latest official updates, open public "
        "comments and deadlines, and their original Japanese sources. Updated daily; not legal advice."
    )
    stats = [f"{len(in_area):,} updates tracked", f"{ai_count:,} with AI summaries",
             f"{len(open_items):,} open public comments"]
    if updated:
        stats.append(f"last checked {updated.isoformat()}")

    parts = [
        f'    <p class="area-page-intro">Official Japanese developments on {escape(page.topics)}, '
        "monitored daily from government, regulator, Diet, and self-regulatory sources and labelled in "
        f"English for triage. {escape(AREA_LABEL_NOTICE)}</p>",
        f'    <p class="area-page-stats">{escape(" · ".join(stats))}</p>',
        '    <p class="area-page-actions">',
        f'      <a class="area-page-action" href="{escape(dashboard_area_url(page))}">Search and filter this area in the dashboard</a>',
        f'      <a class="area-page-action" href="../../feeds/{channel.value}.xml">RSS feed</a>',
        f'      <a class="area-page-action" href="../../feeds/{channel.value}.ics">Deadline calendar (.ics)</a>',
        "    </p>",
    ]
    if open_items:
        parts += [
            '    <section class="area-page-section" aria-labelledby="open-comments-title">',
            '      <h2 id="open-comments-title">Open public comments</h2>',
            '      <p class="static-latest-note">Consultations still accepting comments, soonest deadline first. '
            "Confirm the deadline and submission method in the official source.</p>",
            render_item_list(open_items[:AREA_OPEN_COMMENTS_COUNT], show_area=False, show_deadline=True),
            "    </section>",
        ]
    parts += [
        '    <section class="area-page-section" aria-labelledby="latest-title">',
        '      <h2 id="latest-title">Latest updates</h2>',
        '      <p class="static-latest-note">Newest official publications first.</p>',
        render_item_list(latest, show_area=False) if latest else '      <p>No dated updates yet.</p>',
        "    </section>",
    ]
    sources = top_sources(in_area, AREA_TOP_SOURCES)
    if sources:
        rows = "\n".join(f"        <li>{escape(name)} ({count:,})</li>" for name, count in sources)
        parts += [
            '    <section class="area-page-section" aria-labelledby="sources-title">',
            '      <h2 id="sources-title">Most frequent sources in this area</h2>',
            f'      <ul class="area-page-sources">\n{rows}\n      </ul>',
            "    </section>",
        ]
    return render_page(
        path=area_page_path(page),
        title=f"{page.heading} — Japan Legal Reform Watch",
        description=description,
        heading=page.heading,
        breadcrumb=channel.label,
        body="\n".join(parts),
        current=page.slug,
    )


def render_public_comments_page(items: Sequence[Mapping[str, Any]], today: date) -> str:
    open_items = open_comments(items, today)
    updated = latest_checked(items)
    stats = [f"{len(open_items):,} open public comments with a published deadline"]
    if updated:
        stats.append(f"last checked {updated.isoformat()}")
    parts = [
        '    <p class="area-page-intro">Japanese government and self-regulatory public comment procedures '
        "(パブリックコメント) that are still accepting comments, soonest deadline first, across every area "
        "this dashboard monitors. Deadlines come only from structured fields in e-Gov, JPX, and JSDA "
        "listings; consultations without a structured deadline are not shown here.</p>",
        f'    <p class="area-page-stats">{escape(" · ".join(stats))}</p>',
        '    <p class="area-page-actions">',
        f'      <a class="area-page-action" href="{escape(SITE_URL + "?" + urlencode({"stage": "Public Comment Open"}))}">Search open public comments in the dashboard</a>',
        '      <a class="area-page-action" href="../feeds/all.ics">Deadline calendar (.ics)</a>',
        "    </p>",
        '    <section class="area-page-section" aria-labelledby="open-comments-title">',
        '      <h2 id="open-comments-title">Open public comments</h2>',
        '      <p class="static-latest-note">Confirm the deadline and submission method in the official source.</p>',
        render_item_list(open_items, show_deadline=True) if open_items
        else "      <p>No open public comments with a published deadline right now.</p>",
        "    </section>",
    ]
    return render_page(
        path=f"{PUBLIC_COMMENTS_DIR_NAME}/",
        title="Open Japan Public Comments and Deadlines — Japan Legal Reform Watch",
        description=(
            "Japanese public comment consultations still accepting comments, with deadlines, English titles, "
            "and links to the official e-Gov, JPX, and JSDA sources. Updated daily; not legal advice."
        ),
        heading=PUBLIC_COMMENTS_HEADING,
        breadcrumb="Open public comments",
        body="\n".join(parts),
        current=PUBLIC_COMMENTS_DIR_NAME,
    )


def render_sitemap(entries: Sequence[tuple[str, date | None]]) -> str:
    lines = ['<?xml version="1.0" encoding="UTF-8"?>', '<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">']
    for loc, lastmod in entries:
        lines.append("  <url>")
        lines.append(f"    <loc>{xml_escape(loc)}</loc>")
        if lastmod:
            lines.append(f"    <lastmod>{lastmod.isoformat()}</lastmod>")
        lines.append("  </url>")
    lines.append("</urlset>")
    return "\n".join(lines) + "\n"


# ------------------------------------------------------------------- writing


def write_if_changed(path: Path, text: str) -> bool:
    if path.exists() and path.read_text(encoding="utf-8") == text:
        return False
    path.parent.mkdir(parents=True, exist_ok=True)
    write_text_atomic(path, text)
    return True


def build(
    data_path: Path,
    index_path: Path,
    sitemap_path: Path,
    today: date,
    site_dir: Path | None = None,
) -> dict[str, Any]:
    site_dir = site_dir or index_path.parent
    items = load_items(data_path)
    updated = latest_checked(items)

    html = index_path.read_text(encoding="utf-8")
    html = replace_static_block(html, render_static_latest(latest_items(items, today, STATIC_LATEST_COUNT), updated))
    html = replace_block(html, AREA_NAV_START, AREA_NAV_END, render_area_nav())
    changed = {"index": write_if_changed(index_path, html)}

    sitemap_entries: list[tuple[str, date | None]] = [(SITE_URL, updated)]
    for page in AREA_PAGES:
        path = area_page_path(page)
        changed[path] = write_if_changed(site_dir / path / "index.html", render_area_page(page, items, today))
        sitemap_entries.append((SITE_URL + path, latest_checked(area_items(items, page))))
    path = f"{PUBLIC_COMMENTS_DIR_NAME}/"
    changed[path] = write_if_changed(site_dir / path / "index.html", render_public_comments_page(items, today))
    sitemap_entries.append((SITE_URL + path, updated))
    sitemap_entries += [(SITE_URL + path, None) for path in STATIC_SITEMAP_PATHS]
    changed["sitemap"] = write_if_changed(sitemap_path, render_sitemap(sitemap_entries))

    return {
        "pages_written": len(AREA_PAGES) + 1,
        "files_changed": sorted(name for name, was_changed in changed.items() if was_changed),
    }


def main(argv: Sequence[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--data", type=Path, default=DATA_PATH)
    parser.add_argument("--index", type=Path, default=INDEX_PATH)
    parser.add_argument("--sitemap", type=Path, default=SITEMAP_PATH)
    parser.add_argument("--today", type=date.fromisoformat, default=None, help="JST date (YYYY-MM-DD)")
    args = parser.parse_args(argv)
    today = args.today or datetime.now(JST).date()
    print(json.dumps(build(args.data, args.index, args.sitemap, today), sort_keys=True))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
